### ISSUE TITLE
Use dependabot for your dependencies...

### ISSUE THREAD

**Issue by tschm** [VanekPetr/investment-funnel#110]
copy 

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

into .github/dependabot.yml
